### ISSUE TITLE
Missing Value from DIGGScodes.xml

### ISSUE THREAD

**Issue by sdeaton75** [DIGGSml/DIGGSml.github.io#2]
The DIGGSCodes.xml may be missing a property for the LabPenetrometerTest result.  There is the abstract test procedure, but this particular one is missing the property for results. In the image below, I have added a proposed property.

![image](https://user-images.githubusercontent.com/2412948/34524226-b7de6d0a-f068-11e7-8e43-e5cac103e585.png)

**Comment by sdeaton75** [comment]
I also noticed there are various other abstract test procedures that are missing results.  LabResistivity is another example.

**Comment by nickmachairas** [comment]
This issue was moved to DIGGSml/diggs-schema#2
